version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: hao
      POSTGRES_PASSWORD: suisui0322
      POSTGRES_DB: eccmfa
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: hao@gmail.com
      PGADMIN_DEFAULT_PASSWORD: suisui0322
    ports:
      - "8080:80"
    depends_on:
      - db
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data: